services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: bibliotroca
    stdin_open: true
    tty: true
    ports:
      - "8000:8000"
      - "9003:9003"
      - "5173:5173"
    volumes:
      - type: bind
        source: ./app
        target: /var/www/html
    networks:
      - docker_default
    restart: no
  mongodb:
    container_name: mongodb
    image: mongodb/mongodb-community-server:8.0-ubi8
    environment:
      - MONGO_INITDB_ROOT_USERNAME=root
      - MONGO_INITDB_ROOT_PASSWORD=mm3Ck868jJ
    ports:
      - "27017:27017"
    networks:
      - docker_default
volumes:
  mysql_data:
    external: true
networks:
    docker_default:
      external: true
